[workspace]
authors = ["Liangliang Zhu <shinyypig@gmail.com>"]
channels = ["conda-forge"]
name = "code"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.1,<3"
pip = ">=25.1.1,<26"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.3,<4"
plotly = ">=6.2.0,<7"
jupyter = ">=1.1.1,<2"
pandas = ">=2.3.1,<3"
cvxpy = ">=1.7.2,<2"
tensorly = ">=0.8.2,<0.9"

[pypi-dependencies]
opencv-python = ">=4.11.0.86, <5"
rpca = ">=0.1.6, <0.2"
